#!/usr/bin/env python3
"""Generate sample PDF/DOCX files for the Research Vault resource seed.

Run with: docker exec -i acc-minio python3 - < seed-resources.make-files.py

Produces real (minimal but valid) PDF and DOCX files and uploads them to the
acc-media bucket under keys research-vault/<file>. Bytes are verified
(non-zero, correct magic bytes) after upload via awslocal s3api head-object.
"""

import sys

BUCKET = "acc-media"

RESOURCES = [
    ("research-vault/research-email-guide.pdf", "PDF"),
    ("research-vault/sop-writing-guide.pdf", "PDF"),
    ("research-vault/phd-application-checklist.pdf", "PDF"),
    ("research-vault/grant-writing-template.docx", "DOCX"),
    ("research-vault/lor-template.docx", "DOCX"),
]

def make_pdf(title: str) -> bytes:
    content = (
        f"This is a sample PDF resource for the Research Vault demo. Title: {title}. "
        "You can open it with 'Open PDF' and download it with 'Download'. "
    ) * 12
    stream = f"BT /F1 12 Tf 72 720 Td ({content}) Tj ET".encode("latin-1")
    objects = []
    objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    objects.append(b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>")
    objects.append(b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>")
    objects.append(b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream")
    objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    out = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{i} 0 obj\n".encode() + obj + b"\nendobj\n"
    xref_pos = len(out)
    out += b"xref\n0 " + str(len(objects) + 1).encode() + b"\n"
    out += b"0000000000 65535 f \n"
    for off in offsets[1:]:
        out += f"{off:010d} 00000 n \n".encode()
    out += b"trailer\n<< /Size " + str(len(objects) + 1).encode() + b" /Root 1 0 R >>\nstartxref\n" + str(xref_pos).encode() + b"\n%%EOF\n"
    return bytes(out)

def make_docx(title: str) -> bytes:
    import io, zipfile
    w = 'xmlns="http://schemas.openxmlformats.org/wordprocessingml/2006/main"'
    body = (
        "<w:p><w:r><w:t>Research Vault sample document: "
        f"{title}. This DOCX exercises the Download action for file resources.</w:t></w:r></w:p>"
    )
    document = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        f'<w:document {w}><w:body>{body}</w:body></w:document>'
    )
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml",
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
            '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
            '<Default Extension="xml" ContentType="application/xml"/>'
            '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
            "</Types>")
        z.writestr("_rels/.rels",
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>'
            "</Relationships>")
        z.writestr("word/document.xml", document)
    return buf.getvalue()

def main() -> int:
    import json, subprocess

    for key, kind in RESOURCES:
        title = key.rsplit("/", 1)[1]
        data = make_pdf(title) if kind == "PDF" else make_docx(title)

        # Sanity-check generated bytes before upload.
        if not data or len(data) < 200:
            print(f"FAIL: {key} generated only {len(data)} bytes", file=sys.stderr)
            return 1
        if kind == "PDF" and not data.startswith(b"%PDF"):
            print(f"FAIL: {key} missing %PDF magic", file=sys.stderr)
            return 1
        if kind == "DOCX" and not data.startswith(b"PK"):
            print(f"FAIL: {key} missing PK (zip) magic", file=sys.stderr)
            return 1

        # Upload (idempotent overwrite). awslocal requires a real file path
        # for --body, so stage the bytes in /tmp first.
        tmp = "/tmp/" + key.replace("/", "_")
        with open(tmp, "wb") as f:
            f.write(data)
        p = subprocess.run(
            ["awslocal", "s3api", "put-object", "--bucket", BUCKET, "--key", key, "--body", tmp],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        )
        if p.returncode != 0:
            print(f"FAIL upload {key}: {p.stderr.decode(errors='replace')}", file=sys.stderr)
            return 1

        # Verify stored object exists and byte count matches.
        v = subprocess.run(
            ["awslocal", "s3api", "head-object", "--bucket", BUCKET, "--key", key],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        )
        if v.returncode != 0:
            print(f"FAIL verify {key}: {v.stderr.decode(errors='replace')}", file=sys.stderr)
            return 1
        size = json.loads(v.stdout.decode())["ContentLength"]
        if size != len(data):
            print(f"FAIL verify {key}: stored {size} bytes != generated {len(data)}", file=sys.stderr)
            return 1
        print(f"OK {key} ({size} bytes)")

    return 0

if __name__ == "__main__":
    sys.exit(main())
